version: '3.1'

services:

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/forexdb
    ports:
      - "8080:8080"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: forexdb
    ports:
      - "5432:5432"
